set linesize 300;
set pagesize 50;
column payment_no heading "Payment No.";
column amount heading "Amount";
column account_no heading "Account No.";
column amount format $9,990.90;
column payment_no format A15;
column account_no format A11;
set underline =;
column first_name heading "First Name";
column last_name heading "Last Name";
column first_name format A12;
column last_name format A12;
column fine_due heading 'Fine|Due Amount';
column fine_due format $9,990.90;
column date_joined heading 'Date|Joined';
column book_id heading "Book ID";
column book_title heading "Book Title";
column book_title format A30;
column language heading "Language";
column author heading "Author";
column language format A10;
column author format A20;
column publisher format A20;
column publish_year heading 'Publish|Year';
column date_created heading "Date Created";
column date_created format A12;
column reserve_no heading "Reserve No.";
column reserve_no format A11;
column reserve_date heading "Reserve Date";
column reserve_date format A12;
column collection_date heading 'Collection|Date';
column collection_date format A10;
column return_date heading 'Return|Date';
column return_date format A9;
column fine_no heading "Fine No.";
column fine_no format A8;
column day_count heading "Day Count";
column fine_amount heading "Fine Amount";
column fine_amount format $9,990.90;
column payment_status heading "Payment Status";
column payment_status format A14;
column report_no heading "Report No.";
column report_no format A10;